In [1]:
%tensorflow_version 2.x

In [2]:
import tensorflow as tf
print(tf.version.VERSION)

2.4.1


In [3]:
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [4]:
print(string,string.shape,type(string))
print(number,number.shape,type(number))
print(floating,floating.shape,type(floating),tf.rank(floating))

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'> () <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324> () <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567> () <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'> tf.Tensor(0, shape=(), dtype=int32)


In [5]:
rank_tensor=tf.Variable([
                         [
                          [1,2,3],[4,5,6],[7,8,9]
                         ],[
                            [10,11,12],[13,14,15],[16,17,18]
                         ],[
                            [20,21,22],[23,24,25],[26,27,28]
                         ]
],tf.int32)
rank1_tensor = tf.Variable(["Test","pritam"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
rank3_tensor = tf.Variable("abc",tf.string)
print(tf.rank(rank3_tensor),rank3_tensor.shape)
print(tf.rank(rank1_tensor),rank1_tensor.shape)
print(tf.rank(rank2_tensor),rank2_tensor.shape)
print(tf.rank(rank_tensor),rank_tensor.shape)

tf.Tensor(0, shape=(), dtype=int32) ()
tf.Tensor(1, shape=(), dtype=int32) (2,)
tf.Tensor(2, shape=(), dtype=int32) (2, 2)
tf.Tensor(3, shape=(), dtype=int32) (3, 3, 3)


In [6]:
# we can algo shapes in tuples (x,y,z,....)
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,3]
                                                                             
# The numer of elements in the reshaped tensor MUST match the number in the original

In [7]:
print(tensor1)
print(tensor2)
print(tensor3)
# Notice the changes in shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [8]:
%timeit z=tf.zeros([5,5,5,5,5])

The slowest run took 18.42 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 41.7 µs per loop


In [9]:
z=tf.zeros([5,5,5,5,5])
t=tf.reshape(z,(625*5,))
print(t)

tf.Tensor([0. 0. 0. ... 0. 0. 0.], shape=(3125,), dtype=float32)


In [10]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [11]:
tensor[::2,::2]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  3,  5],
       [11, 13, 15]], dtype=int32)>

In [12]:
x=tf.ones((5,5,5,5))
x[::3,::3,::3,::3]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>